export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';

export const LOGIN_ADMIN_REQUEST = 'LOGIN_ADMIN_REQUEST';
export const LOGIN_ADMIN_SUCCESS = 'LOGIN_ADMIN_SUCCESS';
export const LOGIN_ADMIN_FAILED = 'LOGIN_ADMIN_FAILED';
export const LOGOUT_ADMIN = 'LOGOUT_ADMIN';
export const CHECK_ADMIN_AUTHENTICATED = 'CHECK_ADMIN_AUTHENTICATED';
export const LOAD_EMPLOYEE_LIST = 'LOAD_EMPLOYEE_LIST';
export const LOAD_EMPLOYEE_LIST_SUCCESS = 'LOAD_EMPLOYEE_LIST_SUCCESS';
export const ADD_EMPLOYEE_REQUEST = 'ADD_EMPLOYEE_REQUEST';
export const DELETE_EMPLOYEE_REQUEST = 'DELETE_EMPLOYEE_REQUEST';

export const LOGIN_EMPLOYEE_REQUEST = 'LOGIN_EMPLOYEE_REQUEST';
export const LOGIN_EMPLOYEE_SUCCESS = 'LOGIN_EMPLOYEE_SUCCESS';
export const LOGIN_EMPLOYEE_FAILED = 'LOGIN_EMPLOYEE_FAILED';
export const LOGOUT_EMPLOYEE = 'LOGOUT_EMPLOYEE';
export const CHECK_EMPLOYEE_AUTHENTICATED = 'CHECK_EMPLOYEE_AUTHENTICATED';

// export const LOGIN_USER_REQUEST = 'AUTH/LOGIN_USER_REQUEST';
// export const LOGIN_USER_SUCCESS = 'AUTH/LOGIN_USER_SUCCESS';
// export const LOGIN_USER_FAILED = 'AUTH/LOGIN_USER_FAILED';

// export const RESET_LOGIN_ERROR = 'AUTH/RESET_LOGIN_ERROR';

// export const CHECK_USER_AUTHENTICATED = 'AUTH/CHECK_USER_AUTHENTICATED';

// export const CHANGE_LOGIN_VALUES = 'AUTH/CHANGE_LOGIN_VALUES';

// export const LOGOUT_USER = 'AUTH/LOGOUT_USER';
// export const CLEAR_REDUX_STORE = 'AUTH/CLEAR_REDUX_STORE';

// export const GET_INITIAL_REQUESTS = 'AUTH/GET_INITIAL_REQUESTS';
// export const GET_PUBLIC_INITIAL_REQUESTS = 'AUTH/GET_PUBLIC_INITIAL_REQUESTS';

// export const LOGIN_FLOW_REQUEST = 'AUTH/LOGIN_FLOW_REQUEST';
// export const LOGIN_FLOW_START_LOADING = 'AUTH/LOGIN_FLOW_START_LOADING';
// export const LOGIN_FLOW_STOP_LOADING = 'AUTH/LOGIN_FLOW_STOP_LOADING';
