mutation AssignReviewers($input: CreateAssignmentInput!) {
  CreateAssignment(input: $input) {
    assignments {
      id
      reviewee {
        id
        assignmentStats {
          progress
          completed
          total
        }
      }
    }
  }
}
