#import "../../fragments/User.gql"
mutation AssignReviewers($input: CreateAssignmentInput!) {
  CreateAssignment(input: $input) {
    assignments {
      id
      review {
        id
        attitude
        communication
        growth
        dependability
        productivity
        initiative
        innovation
        comment
        rating
      }
      reviewee {
        ...User
        assignmentStats {
          progress
          completed
          total
        }
      }
    }
  }
}
